linters:
  enable-all: true
  disable:
    - funlen
    - depguard
    - godot
    - lll
    - gomnd
    - nestif
    - nlreturn
    - wsl
    - ifshort
    - nosnakecase
    - gci
    - gochecknoinits
    - tagliatelle
    - gocognit
    - inamedparam
    - testpackage
    - goconst
    - gofumpt
    - scopelint
    - mnd
    - intrange
  fast: true

issues:
  exclude-rules:
    - path: 'api/v1/handlers/scanner_(.+)\.go'
      linters:
        - dupl
    - path: 'worker/(.+)\.go'
      linters:
        - dupl
    - path: 'tasks/nats/(.+)\.go'
      linters:
        - dupl