version: "3.8"

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - licenta-network

  application:
    build: .
    ports:
      - "5001:5000"
    networks:
      - licenta-network
    depends_on:
      - db
      - nats
      - redis
    env_file:
      - docker.env

  nats-worker:
    build: .
    command: nats
    networks:
      - licenta-network
    depends_on:
      - db
      - nats
    env_file:
      - docker.env

  swagger:
    image: swaggerapi/swagger-ui
    networks:
      - licenta-network
    ports:
      - "5002:8080"
    volumes:
      - ./api/v1/spec.yaml:/swagger.json:ro
    environment:
      - SWAGGER_JSON=/swagger.json

  db:
    build:
      context: postgres/
    networks:
      - licenta-network
    ports:
      - "1001:5432"
    env_file:
      - docker.env

  nats:
    image: nats:latest
    command: -DV
    ports:
      - "4222:4222"
    networks:
      - licenta-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - licenta-network
    depends_on:
      - application
    environment:
      - PUBLIC_BACKEND_URL=http://application:5000
      - ORIGIN=http://localhost:5003

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "5003:80"
    networks:
      - licenta-network
    depends_on:
      - application
      - frontend
    environment:
      - UPSTREAM_API=application:5000
      - UPSTREAM_FRONTEND=frontend:3000

  otelcollector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yml:/etc/otelcol-contrib/config.yaml
    networks:
      - licenta-network
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension

  jaeger:
    image: jaegertracing/all-in-one:${JAEGER_IMAGE_TAG:-latest}
    volumes:
      - "./jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    networks:
      - licenta-network
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=${PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR:-true}
      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
      - PROMETHEUS_QUERY_DURATION_UNIT=${PROMETHEUS_QUERY_DURATION_UNIT:-}
      - PROMETHEUS_QUERY_NORMALIZE_CALLS=true
      - PROMETHEUS_QUERY_NORMALIZE_DURATION=true
    ports:
      - "16686:16686"

  prometheus:
    image: prom/prometheus:latest
    networks:
      - licenta-network
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

networks:
  licenta-network:
    driver: bridge
