version: "3.8"

services:
  application:
    build: .
    ports:
      - "5001:5000"
    networks:
      - licenta-network
    depends_on:
      - db
    env_file:
      - docker.env

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "5002:8080"
    networks:
      - licenta-network
    volumes:
      - ./api/v1/spec.yaml:/swagger.json:ro
    environment:
      - SWAGGER_JSON=/swagger.json

  db:
    image: postgres:latest
    ports:
      - "1001:5432"
    networks:
      - licenta-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: licenta

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "5003:80"
    networks:
      - licenta-network
    depends_on:
      - application
    environment:
      - UPSTREAM=application:5000

networks:
  licenta-network:
    driver: bridge
