version: "3.8"

services:
  application:
    build: .
    ports:
      - "5001:5000"
    networks:
      - licenta-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    ports:
      - "1001:5432"
    networks:
      - licenta-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: licenta

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "5002:80"
    networks:
      - licenta-network
    depends_on:
      - application
    environment:
      - UPSTREAM=application:5000

networks:
  licenta-network:
    driver: bridge
