// Code generated by qtc from "scan-failed.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line scan-failed.qtpl:1
package templates

//line scan-failed.qtpl:1
import "github.com/tedyst/licenta/db/queries"

//line scan-failed.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line scan-failed.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line scan-failed.qtpl:3
func StreamSendScanFailedEmail(qw422016 *qt422016.Writer, scanId int, scanGroupID int, results []*queries.ScanResult) {
//line scan-failed.qtpl:3
	qw422016.N().S(`
	The scan with ID `)
//line scan-failed.qtpl:4
	qw422016.N().D(scanId)
//line scan-failed.qtpl:4
	qw422016.N().S(` has failed. The scan group ID is `)
//line scan-failed.qtpl:4
	qw422016.N().D(scanGroupID)
//line scan-failed.qtpl:4
	qw422016.N().S(`.
    Here are the results:
    <ul>
    `)
//line scan-failed.qtpl:7
	for _, result := range results {
//line scan-failed.qtpl:7
		qw422016.N().S(`
        <li>`)
//line scan-failed.qtpl:8
		qw422016.E().S(result.Message)
//line scan-failed.qtpl:8
		qw422016.N().S(`</li>
    `)
//line scan-failed.qtpl:9
	}
//line scan-failed.qtpl:9
	qw422016.N().S(`
    </ul>
`)
//line scan-failed.qtpl:11
}

//line scan-failed.qtpl:11
func WriteSendScanFailedEmail(qq422016 qtio422016.Writer, scanId int, scanGroupID int, results []*queries.ScanResult) {
//line scan-failed.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line scan-failed.qtpl:11
	StreamSendScanFailedEmail(qw422016, scanId, scanGroupID, results)
//line scan-failed.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line scan-failed.qtpl:11
}

//line scan-failed.qtpl:11
func SendScanFailedEmail(scanId int, scanGroupID int, results []*queries.ScanResult) string {
//line scan-failed.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line scan-failed.qtpl:11
	WriteSendScanFailedEmail(qb422016, scanId, scanGroupID, results)
//line scan-failed.qtpl:11
	qs422016 := string(qb422016.B)
//line scan-failed.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line scan-failed.qtpl:11
	return qs422016
//line scan-failed.qtpl:11
}
