services:
  redis:
    image: redis:latest
    volumes:
      - ./redis.yml:/usr/local/etc/redis/redis.conf
    networks:
      - demo-network

  worker:
    build:
      context: ../
    command: worker
    env_file:
      - .env
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
