services:
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ./redis.yml:/etc/redis/redis.conf
    networks:
      - demo-network

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    networks:
      - demo-network

  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - demo-network
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: mysql
    networks:
      - demo-network
    env_file:
      - .env

  worker:
    build:
      context: ../
    command: worker
    container_name: worker
    env_file:
      - .env
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
