// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: copyfrom.go

package queries

import (
	"context"
)

// iteratorForCreateDockerLayerResultsForProject implements pgx.CopyFromSource.
type iteratorForCreateDockerLayerResultsForProject struct {
	rows                 []CreateDockerLayerResultsForProjectParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateDockerLayerResultsForProject) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateDockerLayerResultsForProject) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProjectID,
		r.rows[0].LayerID,
		r.rows[0].Name,
		r.rows[0].Line,
		r.rows[0].LineNumber,
		r.rows[0].Match,
		r.rows[0].Probability,
		r.rows[0].Username,
		r.rows[0].Password,
		r.rows[0].Filename,
	}, nil
}

func (r iteratorForCreateDockerLayerResultsForProject) Err() error {
	return nil
}

func (q *Queries) CreateDockerLayerResultsForProject(ctx context.Context, arg []CreateDockerLayerResultsForProjectParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"docker_results"}, []string{"project_id", "layer_id", "name", "line", "line_number", "match", "probability", "username", "password", "filename"}, &iteratorForCreateDockerLayerResultsForProject{rows: arg})
}

// iteratorForCreateGitResultForCommit implements pgx.CopyFromSource.
type iteratorForCreateGitResultForCommit struct {
	rows                 []CreateGitResultForCommitParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateGitResultForCommit) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateGitResultForCommit) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Commit,
		r.rows[0].Name,
		r.rows[0].Line,
		r.rows[0].LineNumber,
		r.rows[0].Match,
		r.rows[0].Probability,
		r.rows[0].Username,
		r.rows[0].Password,
		r.rows[0].Filename,
	}, nil
}

func (r iteratorForCreateGitResultForCommit) Err() error {
	return nil
}

func (q *Queries) CreateGitResultForCommit(ctx context.Context, arg []CreateGitResultForCommitParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"git_results"}, []string{"commit", "name", "line", "line_number", "match", "probability", "username", "password", "filename"}, &iteratorForCreateGitResultForCommit{rows: arg})
}
