// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             int64
	OrganizationID int64
	UserID         int64
	Role           int32
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID             int64
	Name           string
	OrganizationID int64
	CreatedAt      pgtype.Timestamptz
}

type ProjectDockerImage struct {
	ID                                  int64
	ProjectID                           int64
	DockerImage                         string
	Username                            sql.NullString
	Password                            sql.NullString
	MinProbability                      sql.NullFloat64
	UseDefaultWordsReduceProbability    bool
	UseDefaultWordsIncreaseProbability  bool
	UseDefaultPasswordsCompletelyIgnore bool
	UseDefaultUsernamesCompletelyIgnore bool
	ProbailityDecreaseMultiplier        sql.NullFloat64
	ProbabilityIncreaseMultiplier       sql.NullFloat64
	EntropyThreshold                    sql.NullInt32
	LogisticGrowthRate                  sql.NullFloat64
	CreatedAt                           pgtype.Timestamptz
}

type ProjectDockerLayerResult struct {
	ID          int64
	ProjectID   int64
	Layer       int64
	Name        string
	Line        string
	LineNumber  int32
	Match       string
	Probability float64
	Username    sql.NullString
	Password    sql.NullString
	Filename    string
	CreatedAt   pgtype.Timestamptz
}

type ProjectDockerLayerScan struct {
	ID            int64
	ProjectID     int64
	DockerImage   int64
	Finished      bool
	ScannedLayers int32
	LayersToScan  int32
	CreatedAt     pgtype.Timestamptz
}

type ProjectDockerScannedLayer struct {
	ID        int64
	ProjectID int64
	LayerHash string
	ScannedAt pgtype.Timestamptz
}

type ProjectGitRepository struct {
	ID            int64
	ProjectID     int64
	GitRepository string
	Username      sql.NullString
	Password      sql.NullString
	PrivateKey    sql.NullString
	CreatedAt     pgtype.Timestamptz
}

type ProjectGitResult struct {
	ID          int64
	ProjectID   int64
	Commit      int64
	Name        string
	Line        string
	LineNumber  int32
	Match       string
	Probability float64
	Username    sql.NullString
	Password    sql.NullString
	Filename    string
	CreatedAt   pgtype.Timestamptz
}

type ProjectGitScannedCommit struct {
	ID         int64
	ProjectID  int64
	CommitHash string
	CreatedAt  pgtype.Timestamptz
}

type ProjectMember struct {
	ID        int64
	ProjectID int64
	UserID    int64
	Role      int16
	CreatedAt pgtype.Timestamptz
}

type ResetPasswordToken struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Valid     bool
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Scope     []string
	CreatedAt pgtype.Timestamptz
}

type TotpSecretToken struct {
	ID         int64
	UserID     int64
	Valid      bool
	TotpSecret string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamptz
}
