// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BruteforcedPassword struct {
	ID               int64
	Hash             string
	Username         string
	Password         sql.NullString
	LastBruteforceID sql.NullInt64
}

type DefaultBruteforcePassword struct {
	ID       int64
	Password string
}

type NvdCfe struct {
	ID           int64
	CveID        string
	Description  string
	Published    pgtype.Timestamptz
	LastModified pgtype.Timestamptz
	Score        float64
	CreatedAt    pgtype.Timestamptz
}

type NvdCpe struct {
	ID           int64
	Cpe          string
	DatabaseType int32
	Version      string
	LastModified pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
}

type NvdCveCpe struct {
	ID    int64
	CveID int64
	CpeID int64
}

type Organization struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             int64
	OrganizationID int64
	UserID         int64
	Role           int32
	CreatedAt      pgtype.Timestamptz
}

type PostgresDatabase struct {
	ID           int64
	ProjectID    int64
	Host         string
	Port         int32
	DatabaseName string
	Username     string
	Password     string
	CreatedAt    pgtype.Timestamptz
}

type PostgresScan struct {
	ID                 int64
	PostgresDatabaseID int64
	Status             int32
	Error              sql.NullString
	CreatedAt          pgtype.Timestamptz
	EndedAt            pgtype.Timestamptz
}

type PostgresScanBruteforceResult struct {
	ID             int64
	PostgresScanID int64
	Username       string
	Password       sql.NullString
	Total          int32
	Tried          int32
	CreatedAt      pgtype.Timestamptz
}

type PostgresScanResult struct {
	ID             int64
	PostgresScanID int64
	Severity       int32
	Message        string
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID             int64
	Name           string
	OrganizationID int64
	CreatedAt      pgtype.Timestamptz
}

type ProjectDockerImage struct {
	ID                                  int64
	ProjectID                           int64
	DockerImage                         string
	Username                            sql.NullString
	Password                            sql.NullString
	MinProbability                      sql.NullFloat64
	UseDefaultWordsReduceProbability    bool
	UseDefaultWordsIncreaseProbability  bool
	UseDefaultPasswordsCompletelyIgnore bool
	UseDefaultUsernamesCompletelyIgnore bool
	ProbailityDecreaseMultiplier        sql.NullFloat64
	ProbabilityIncreaseMultiplier       sql.NullFloat64
	EntropyThreshold                    sql.NullInt32
	LogisticGrowthRate                  sql.NullFloat64
	CreatedAt                           pgtype.Timestamptz
}

type ProjectDockerLayerResult struct {
	ID          int64
	ProjectID   int64
	Layer       int64
	Name        string
	Line        string
	LineNumber  int32
	Match       string
	Probability float64
	Username    sql.NullString
	Password    sql.NullString
	Filename    string
	CreatedAt   pgtype.Timestamptz
}

type ProjectDockerLayerScan struct {
	ID            int64
	ProjectID     int64
	DockerImage   int64
	Finished      bool
	ScannedLayers int32
	LayersToScan  int32
	CreatedAt     pgtype.Timestamptz
}

type ProjectDockerScannedLayer struct {
	ID        int64
	ProjectID int64
	LayerHash string
	ScannedAt pgtype.Timestamptz
}

type ProjectGitRepository struct {
	ID            int64
	ProjectID     int64
	GitRepository string
	Username      sql.NullString
	Password      sql.NullString
	PrivateKey    sql.NullString
	CreatedAt     pgtype.Timestamptz
}

type ProjectGitResult struct {
	ID          int64
	ProjectID   int64
	Commit      int64
	Name        string
	Line        string
	LineNumber  int32
	Match       string
	Probability float64
	Username    sql.NullString
	Password    sql.NullString
	Filename    string
	CreatedAt   pgtype.Timestamptz
}

type ProjectGitScannedCommit struct {
	ID         int64
	ProjectID  int64
	CommitHash string
	CreatedAt  pgtype.Timestamptz
}

type ProjectMember struct {
	ID        int64
	ProjectID int64
	UserID    int64
	Role      int16
	CreatedAt pgtype.Timestamptz
}

type ResetPasswordToken struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Valid     bool
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Scope     []string
	CreatedAt pgtype.Timestamptz
}

type TotpSecretToken struct {
	ID         int64
	UserID     int64
	Valid      bool
	TotpSecret string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamptz
}
