// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0

package queries

import (
	"database/sql"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Organization struct {
	ID        int64
	Name      string
	CreatedAt pgtype.Timestamptz
}

type OrganizationMember struct {
	ID             int64
	OrganizationID int64
	UserID         int64
	Role           int32
	CreatedAt      pgtype.Timestamptz
}

type Project struct {
	ID             int64
	Name           string
	OrganizationID int64
	CreatedAt      pgtype.Timestamptz
}

type ProjectMember struct {
	ID        int64
	ProjectID int64
	UserID    int64
	Role      int16
	CreatedAt pgtype.Timestamptz
}

type ResetPasswordToken struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Valid     bool
	CreatedAt pgtype.Timestamptz
}

type Session struct {
	ID        uuid.UUID
	UserID    sql.NullInt64
	Scope     []string
	CreatedAt pgtype.Timestamptz
}

type TotpSecretToken struct {
	ID         int64
	UserID     int64
	Valid      bool
	TotpSecret string
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID        int64
	Username  string
	Password  string
	Email     string
	CreatedAt pgtype.Timestamptz
}
