// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: mongo.sql

package queries

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMongoDatabase = `-- name: CreateMongoDatabase :one
INSERT INTO mongo_databases(project_id, database_name, host, port, username, PASSWORD, version)
    VALUES ($1, $2, $3, $4, encrypt_data($1, $6, $7), encrypt_data($1, $6, $8), $5)
RETURNING
    id, project_id, host, port, database_name, username, password, version, created_at
`

type CreateMongoDatabaseParams struct {
	ProjectID    int64          `json:"project_id"`
	DatabaseName string         `json:"database_name"`
	Host         string         `json:"host"`
	Port         int32          `json:"port"`
	Version      sql.NullString `json:"version"`
	SaltKey      string         `json:"salt_key"`
	Username     string         `json:"username"`
	Password     string         `json:"password"`
}

func (q *Queries) CreateMongoDatabase(ctx context.Context, arg CreateMongoDatabaseParams) (*MongoDatabase, error) {
	row := q.db.QueryRow(ctx, createMongoDatabase,
		arg.ProjectID,
		arg.DatabaseName,
		arg.Host,
		arg.Port,
		arg.Version,
		arg.SaltKey,
		arg.Username,
		arg.Password,
	)
	var i MongoDatabase
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.Version,
		&i.CreatedAt,
	)
	return &i, err
}

const createMongoScan = `-- name: CreateMongoScan :one
INSERT INTO mongo_scans(scan_id, database_id)
    VALUES ($1, $2)
RETURNING
    id, scan_id, database_id
`

type CreateMongoScanParams struct {
	ScanID     int64 `json:"scan_id"`
	DatabaseID int64 `json:"database_id"`
}

func (q *Queries) CreateMongoScan(ctx context.Context, arg CreateMongoScanParams) (*MongoScan, error) {
	row := q.db.QueryRow(ctx, createMongoScan, arg.ScanID, arg.DatabaseID)
	var i MongoScan
	err := row.Scan(&i.ID, &i.ScanID, &i.DatabaseID)
	return &i, err
}

const deleteMongoDatabase = `-- name: DeleteMongoDatabase :exec
DELETE FROM mongo_databases
WHERE id = $1
`

func (q *Queries) DeleteMongoDatabase(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteMongoDatabase, id)
	return err
}

const getMongoDatabase = `-- name: GetMongoDatabase :one
SELECT
    id,
    project_id,
    host,
    port,
    database_name,
    decrypt_data(project_id, $2, username) AS username,
    decrypt_data(project_id, $2, PASSWORD) AS PASSWORD,
    version,
    created_at,
(
        SELECT
            COUNT(*)
        FROM
            mongo_scans
        WHERE
            mongo_scans.database_id = mongo_databases.id) AS scan_count
FROM
    mongo_databases
WHERE
    mongo_databases.id = $1
`

type GetMongoDatabaseParams struct {
	ID      int64  `json:"id"`
	SaltKey string `json:"salt_key"`
}

type GetMongoDatabaseRow struct {
	ID           int64              `json:"id"`
	ProjectID    int64              `json:"project_id"`
	Host         string             `json:"host"`
	Port         int32              `json:"port"`
	DatabaseName string             `json:"database_name"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	Version      sql.NullString     `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ScanCount    int64              `json:"scan_count"`
}

func (q *Queries) GetMongoDatabase(ctx context.Context, arg GetMongoDatabaseParams) (*GetMongoDatabaseRow, error) {
	row := q.db.QueryRow(ctx, getMongoDatabase, arg.ID, arg.SaltKey)
	var i GetMongoDatabaseRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Host,
		&i.Port,
		&i.DatabaseName,
		&i.Username,
		&i.Password,
		&i.Version,
		&i.CreatedAt,
		&i.ScanCount,
	)
	return &i, err
}

const getMongoDatabasesForProject = `-- name: GetMongoDatabasesForProject :many
SELECT
    id,
    project_id,
    host,
    port,
    database_name,
    decrypt_data(project_id, $2, username) AS username,
    decrypt_data(project_id, $2, PASSWORD) AS PASSWORD,
    version,
    created_at
FROM
    mongo_databases
WHERE
    project_id = $1
`

type GetMongoDatabasesForProjectParams struct {
	ProjectID int64  `json:"project_id"`
	SaltKey   string `json:"salt_key"`
}

type GetMongoDatabasesForProjectRow struct {
	ID           int64              `json:"id"`
	ProjectID    int64              `json:"project_id"`
	Host         string             `json:"host"`
	Port         int32              `json:"port"`
	DatabaseName string             `json:"database_name"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	Version      sql.NullString     `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetMongoDatabasesForProject(ctx context.Context, arg GetMongoDatabasesForProjectParams) ([]*GetMongoDatabasesForProjectRow, error) {
	rows, err := q.db.Query(ctx, getMongoDatabasesForProject, arg.ProjectID, arg.SaltKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetMongoDatabasesForProjectRow
	for rows.Next() {
		var i GetMongoDatabasesForProjectRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Host,
			&i.Port,
			&i.DatabaseName,
			&i.Username,
			&i.Password,
			&i.Version,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMongoScan = `-- name: GetMongoScan :one
SELECT
    id, scan_id, database_id
FROM
    mongo_scans
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetMongoScan(ctx context.Context, id int64) (*MongoScan, error) {
	row := q.db.QueryRow(ctx, getMongoScan, id)
	var i MongoScan
	err := row.Scan(&i.ID, &i.ScanID, &i.DatabaseID)
	return &i, err
}

const getMongoScanByScanID = `-- name: GetMongoScanByScanID :one
SELECT
    id, scan_id, database_id
FROM
    mongo_scans
WHERE
    scan_id = $1
LIMIT 1
`

func (q *Queries) GetMongoScanByScanID(ctx context.Context, scanID int64) (*MongoScan, error) {
	row := q.db.QueryRow(ctx, getMongoScanByScanID, scanID)
	var i MongoScan
	err := row.Scan(&i.ID, &i.ScanID, &i.DatabaseID)
	return &i, err
}

const getProjectInfoForMongoScanByScanID = `-- name: GetProjectInfoForMongoScanByScanID :one
SELECT
    projects.id, projects.name, projects.organization_id, projects.remote, projects.created_at,
    mongo_databases.id AS database_id,
    mongo_databases.project_id AS database_project_id,
    mongo_databases.host AS database_host,
    mongo_databases.port AS database_port,
    mongo_databases.database_name AS database_database_name,
    decrypt_data(mongo_databases.project_id, $2, mongo_databases.username) AS database_username,
    decrypt_data(mongo_databases.project_id, $2, mongo_databases.PASSWORD) AS database_PASSWORD,
    mongo_databases.version AS database_version,
    mongo_databases.created_at AS database_created_at,
    mongo_scans.id, mongo_scans.scan_id, mongo_scans.database_id
FROM
    projects
    JOIN mongo_databases ON mongo_databases.project_id = projects.id
    JOIN mongo_scans ON mongo_scans.database_id = mongo_databases.id
WHERE
    mongo_scans.scan_id = $1
`

type GetProjectInfoForMongoScanByScanIDParams struct {
	ScanID  int64  `json:"scan_id"`
	SaltKey string `json:"salt_key"`
}

type GetProjectInfoForMongoScanByScanIDRow struct {
	Project              Project            `json:"project"`
	DatabaseID           int64              `json:"database_id"`
	DatabaseProjectID    int64              `json:"database_project_id"`
	DatabaseHost         string             `json:"database_host"`
	DatabasePort         int32              `json:"database_port"`
	DatabaseDatabaseName string             `json:"database_database_name"`
	DatabaseUsername     string             `json:"database_username"`
	DatabasePassword     string             `json:"database_password"`
	DatabaseVersion      sql.NullString     `json:"database_version"`
	DatabaseCreatedAt    pgtype.Timestamptz `json:"database_created_at"`
	MongoScan            MongoScan          `json:"mongo_scan"`
}

func (q *Queries) GetProjectInfoForMongoScanByScanID(ctx context.Context, arg GetProjectInfoForMongoScanByScanIDParams) (*GetProjectInfoForMongoScanByScanIDRow, error) {
	row := q.db.QueryRow(ctx, getProjectInfoForMongoScanByScanID, arg.ScanID, arg.SaltKey)
	var i GetProjectInfoForMongoScanByScanIDRow
	err := row.Scan(
		&i.Project.ID,
		&i.Project.Name,
		&i.Project.OrganizationID,
		&i.Project.Remote,
		&i.Project.CreatedAt,
		&i.DatabaseID,
		&i.DatabaseProjectID,
		&i.DatabaseHost,
		&i.DatabasePort,
		&i.DatabaseDatabaseName,
		&i.DatabaseUsername,
		&i.DatabasePassword,
		&i.DatabaseVersion,
		&i.DatabaseCreatedAt,
		&i.MongoScan.ID,
		&i.MongoScan.ScanID,
		&i.MongoScan.DatabaseID,
	)
	return &i, err
}

const updateMongoDatabase = `-- name: UpdateMongoDatabase :exec
UPDATE
    mongo_databases
SET
    database_name = $2,
    host = $3,
    port = $4,
    username = encrypt_data($6, $7, $8),
    PASSWORD = encrypt_data($6, $7, $9),
    version = $5
WHERE
    id = $1
`

type UpdateMongoDatabaseParams struct {
	ID           int64          `json:"id"`
	DatabaseName string         `json:"database_name"`
	Host         string         `json:"host"`
	Port         int32          `json:"port"`
	Version      sql.NullString `json:"version"`
	ProjectID    int64          `json:"project_id"`
	SaltKey      string         `json:"salt_key"`
	Username     string         `json:"username"`
	Password     string         `json:"password"`
}

func (q *Queries) UpdateMongoDatabase(ctx context.Context, arg UpdateMongoDatabaseParams) error {
	_, err := q.db.Exec(ctx, updateMongoDatabase,
		arg.ID,
		arg.DatabaseName,
		arg.Host,
		arg.Port,
		arg.Version,
		arg.ProjectID,
		arg.SaltKey,
		arg.Username,
		arg.Password,
	)
	return err
}

const updateMongoVersion = `-- name: UpdateMongoVersion :exec
UPDATE
    mongo_databases
SET
    version = $2
WHERE
    id = $1
`

type UpdateMongoVersionParams struct {
	ID      int64          `json:"id"`
	Version sql.NullString `json:"version"`
}

func (q *Queries) UpdateMongoVersion(ctx context.Context, arg UpdateMongoVersionParams) error {
	_, err := q.db.Exec(ctx, updateMongoVersion, arg.ID, arg.Version)
	return err
}
