// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: worker.sql

package queries

import (
	"context"
	"database/sql"
)

const bindPostgresScanToWorker = `-- name: BindPostgresScanToWorker :exec
UPDATE
    postgres_scan
SET
    worker_id = $2
WHERE
    id = $1
`

type BindPostgresScanToWorkerParams struct {
	ID       int64         `json:"id"`
	WorkerID sql.NullInt64 `json:"worker_id"`
}

func (q *Queries) BindPostgresScanToWorker(ctx context.Context, arg BindPostgresScanToWorkerParams) error {
	_, err := q.db.Exec(ctx, bindPostgresScanToWorker, arg.ID, arg.WorkerID)
	return err
}

const getWorkerForPostgresScan = `-- name: GetWorkerForPostgresScan :one
SELECT
    workers.id, workers.token, workers.created_at
FROM
    workers
    INNER JOIN postgres_scan ON workers.id = postgres_scan.worker_id
WHERE
    postgres_scan.id = $1
`

type GetWorkerForPostgresScanRow struct {
	Worker Worker `json:"worker"`
}

func (q *Queries) GetWorkerForPostgresScan(ctx context.Context, id int64) (*GetWorkerForPostgresScanRow, error) {
	row := q.db.QueryRow(ctx, getWorkerForPostgresScan, id)
	var i GetWorkerForPostgresScanRow
	err := row.Scan(&i.Worker.ID, &i.Worker.Token, &i.Worker.CreatedAt)
	return &i, err
}

const getWorkersForProject = `-- name: GetWorkersForProject :many
SELECT
    workers.id, workers.token, workers.created_at
FROM
    workers
    INNER JOIN worker_projects ON workers.id = worker_projects.worker_id
WHERE
    worker_projects.project_id = $1
`

type GetWorkersForProjectRow struct {
	Worker Worker `json:"worker"`
}

func (q *Queries) GetWorkersForProject(ctx context.Context, projectID int64) ([]*GetWorkersForProjectRow, error) {
	rows, err := q.db.Query(ctx, getWorkersForProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetWorkersForProjectRow
	for rows.Next() {
		var i GetWorkersForProjectRow
		if err := rows.Scan(&i.Worker.ID, &i.Worker.Token, &i.Worker.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
