basePath: /
definitions:
  v1.PaginationResponse-array_v1_publicUserAPIResponse:
    properties:
      current_page:
        type: integer
      data:
        items:
          $ref: '#/definitions/v1.publicUserAPIResponse'
        type: array
      per_page:
        type: integer
      total_count:
        type: integer
      total_pages:
        type: integer
    type: object
  v1.enableTotpAPIRequest:
    properties:
      totp:
        type: string
    type: object
  v1.loginAPIRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.loginAPIResponse:
    properties:
      status:
        type: string
    type: object
  v1.publicUserAPIResponse:
    properties:
      email:
        type: string
      id:
        type: integer
      username:
        type: string
    type: object
  v1.requestResetPasswordAPIRequest:
    properties:
      email:
        type: string
    type: object
  v1.resetPasswordAPIRequest:
    properties:
      password:
        type: string
      token:
        type: string
    type: object
  v1.setupTOTPResponse:
    properties:
      totp_secret:
        type: string
    type: object
  v1.totpAPIRequest:
    properties:
      totp:
        type: string
    type: object
  v1.userCreateAPIRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Proiect Licenta
  version: "1.0"
paths:
  /api/v1/enable_totp:
    post:
      consumes:
      - application/json
      description: Enable TOTP
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.enableTotpAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Enable TOTP
      tags:
      - auth
  /api/v1/login:
    post:
      consumes:
      - application/json
      description: Login
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.loginAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Login
      tags:
      - auth
  /api/v1/logout:
    post:
      consumes:
      - application/json
      description: Logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Logout
      tags:
      - auth
  /api/v1/request-reset-password:
    post:
      consumes:
      - application/json
      description: Request reset password
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.requestResetPasswordAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Request reset password
      tags:
      - auth
  /api/v1/reset-password:
    post:
      consumes:
      - application/json
      description: Reset password
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.resetPasswordAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Reset password
      tags:
      - auth
  /api/v1/totp:
    post:
      consumes:
      - application/json
      description: Verify TOTP
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.totpAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.loginAPIResponse'
      summary: Verify TOTP
      tags:
      - auth
  /api/v1/totp/setup:
    post:
      consumes:
      - application/json
      description: Generate TOTP
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.setupTOTPResponse'
      summary: Generate TOTP
      tags:
      - auth
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: Get all users
      parameters:
      - default: 0
        description: Page
        in: query
        name: offset
        type: integer
      - default: 10
        description: Limit
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.PaginationResponse-array_v1_publicUserAPIResponse'
      summary: Get users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.userCreateAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.publicUserAPIResponse'
      summary: Create user
      tags:
      - users
  /api/v1/users/{id}:
    get:
      consumes:
      - application/json
      description: Get a user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/v1.userCreateAPIRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.publicUserAPIResponse'
      summary: Get user
      tags:
      - users
swagger: "2.0"
