name: golint-ci
on:
  push:
    branches:
      - master
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          only-new-issues: true

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Test
        run: go test -v ./...

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Get dependencies
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
          go install github.com/valyala/quicktemplate/qtc@latest
      - name: Generate
        run: go generate ./...
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "::error::Go generate has modified some files. Please run 'go generate ./...' locally and commit the changes."
            exit 1
          fi